project:
  type: website
  output-dir: docs
  
website:
  title: "Megan Sears"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - cv.qmd
      
  page-footer:
    background: dark
    left: Copyright 2025, Megan Sears

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full

editor: visual

