project:
  type: website
  output-dir: docs
  
website:
  title: "Megan Sears"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - href: MeganSears_CV.pdf
        text: 'CV'
      
  page-footer:
    background: dark
    left: Copyright 2025, Megan Sears

format:
  html:
    theme: styles.scss
    mainfont: Inter
    toc: true
    page-layout: full
    

editor: visual

